namespace Advent2024.Days;

// https://adventofcode.com/2024/day/8
public sealed class Day08 : MyBaseDay
{
    public override string? Part1TestInput { get; set; } = """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """;

    public Day08() => Input = File.ReadAllText(InputFilePath);

    public override ValueTask<string> Solve_1()
    {
        return new(string.Empty);
    }

    public override ValueTask<string> Solve_2()
    {
        return new(string.Empty);
    }
}
