name: Tests

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"
      - ".editorconfig"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'

jobs:
  build:
    name: "Run Tests"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        global-json-file: ./global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
